-- Generated by Prisma migrate diff against the isolated prior-27 database;
-- CHECK constraints below additionally guard only the new table.
CREATE TYPE "PushPrincipalKind" AS ENUM ('OWNER', 'MEMBER');
CREATE TYPE "PushPlatform" AS ENUM ('APNS');
CREATE TYPE "PushRegistrationStatus" AS ENUM ('ACTIVE', 'REVOKED');

CREATE TABLE "device_push_registrations" (
    "targetKey" UUID NOT NULL,
    "teamId" UUID NOT NULL,
    "principalKind" "PushPrincipalKind" NOT NULL,
    "principalId" UUID NOT NULL,
    "ownerUserId" UUID,
    "notificationMemberId" UUID,
    "installationId" UUID NOT NULL,
    "platform" "PushPlatform" NOT NULL DEFAULT 'APNS',
    "encryptedToken" TEXT,
    "tokenHash" CHAR(64),
    "tokenVersion" INTEGER NOT NULL DEFAULT 1,
    "status" "PushRegistrationStatus" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rotatedAt" TIMESTAMPTZ(3),
    CONSTRAINT "device_push_registrations_pkey" PRIMARY KEY ("targetKey"),
    CONSTRAINT "push_registration_principal_check" CHECK (
      ("principalKind"='OWNER' AND "ownerUserId" IS NOT NULL AND "principalId"="ownerUserId" AND "notificationMemberId" IS NULL)
      OR ("principalKind"='MEMBER' AND "notificationMemberId" IS NOT NULL AND "principalId"="notificationMemberId" AND "ownerUserId" IS NULL)
    ),
    CONSTRAINT "push_registration_version_check" CHECK ("tokenVersion">0),
    CONSTRAINT "push_registration_token_check" CHECK (
      (status='ACTIVE' AND "encryptedToken" IS NOT NULL AND length("encryptedToken")>0 AND "tokenHash" IS NOT NULL AND "tokenHash" ~ '^[0-9a-f]{64}$')
      OR (status='REVOKED' AND "encryptedToken" IS NULL AND "tokenHash" IS NULL)
    )
);
CREATE INDEX "device_push_registrations_teamId_principalKind_principalId__idx" ON "device_push_registrations"("teamId", "principalKind", "principalId", "status");
CREATE UNIQUE INDEX "push_registration_installation_key" ON "device_push_registrations"("teamId", "principalKind", "principalId", "platform", "installationId");
CREATE UNIQUE INDEX "push_registration_token_key" ON "device_push_registrations"("platform", "tokenHash");
ALTER TABLE "device_push_registrations" ADD CONSTRAINT "device_push_registrations_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "device_push_registrations" ADD CONSTRAINT "device_push_registrations_ownerUserId_fkey" FOREIGN KEY ("ownerUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "device_push_registrations" ADD CONSTRAINT "device_push_registrations_notificationMemberId_fkey" FOREIGN KEY ("notificationMemberId") REFERENCES "notification_members"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
