ALTER TYPE "IdentityProvider" ADD VALUE 'MICROSOFT';
ALTER TYPE "IdentityProvider" ADD VALUE 'APPLE';

ALTER TYPE "ChallengeKind" ADD VALUE 'MICROSOFT_OAUTH';
ALTER TYPE "ChallengeKind" ADD VALUE 'APPLE_OAUTH';
